version: '3'
services:
  db:
    image: postgres:13
    container_name: nba_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
